### ISSUE TITLE
Adapt `embassy` to support stm32 target

### ISSUE THREAD

**Issue by Tortoaster** [pendulum-project/statime#140]
### embassy-stm32

Op dit moment ondersteunt de `embassy-stm32` crate alleen de "Normal Tx/Rx DMA descriptors". Om timestamping te kunnen gebruiken moet het de "Enhanced Tx/Rx DMA descriptors" ondersteunen. Hiervoor zijn ook een paar instellingen nodig om onder andere per bericht aan te geven of die getimestampt moet worden. De `stm` example van `statime` bevat nu een kopie van `embassy-stm32`'s `eth` module, met hard-coded enhanced DMA descriptors inclusief extra instellingen. Op zich werkt dat prima, maar mochten we ooit willen updaten naar een nieuwere versie van `embassy`, dan moeten al deze aanpassingen opnieuw toegepast worden op een kopie van de nieuwere code. Daarnaast is deze code nu ook verplichte boilerplate voor iedereen die PTP zou willen draaien op een `stm32` device. Een betere oplossing zou zijn om deze aanpassingen door te voeren in `embassy-stm32` zelf, op een manier waarop dat voor hen acceptabel. Concreet komt dat waarschijnlijk neer op een feature flag om enhanced descriptors aan te zetten, waarbij er ook een aantal extra instellingen per bericht meegestuurd kan worden om te bepalen of timestamping daarvoor van belang is of niet. Afhankelijk van of er concrete use cases zijn om zowel enhanced als normal descriptors te gebruiken, kan het ook zijn dat er geen feature flag bij komt, maar dan moet er gekeken worden naar een begrijpelijke API om hiermee te werken.

Naast de enhanced descriptors zijn er ook een aantal dingen public gemaakt. Namelijk het `tx` veld in de `TxToken` van `embassy`, zodat de `TxToken` van `smoltcp` er naar vertaald kan worden. Hetzelfde geldt voor `rx` in de `RxToken` van `embassy`, en voor de `tx` en `rx` velden in `Ethernet`. Er moet uitgezocht worden of dit echt nodig is (na er nog even naar gekeken te hebben, waarschijnlijk niet), en zo ja, of `embassy-net` dit kan oplossen, of dat dit ook in de PR meegenomen moet worden.

### embassy-net

`embassy-net` is een `embassy` wrapper om `smoltcp` heen. Wanneer `smoltcp` en `embassy-stm32` op bovenstaande manieren aangepast worden, kan het grootste deel van de functionaliteit rondom timestamping van berichten waarschijnlijk ook hierin verwerkt worden. In dat geval hoeven we zelf niet meer direct afhankelijk van smoltcp te zijn, en is de `stm` example eigenlijk alleen nog maar het runnen van de PTP instance en de implementatie van de 4 PTP traits. Dat laatste kunnen we verplaatsen naar een losse `statime-stm32`, zodat eindgebruikers nagenoeg geen boilerplate hebben.

**Comment by diondokter** [comment]
We don't need embassy-net anymore
