### ISSUE TITLE
Bug: Slave_only doesn't do anything.

### ISSUE THREAD

**Issue by davidv1992** [pendulum-project/statime#203]
the slave_only property in defaultDS probably should prevent us from becoming master...

**Comment by folkertdev** [comment]
so, at what level should this happen? the spec is not clear on this. E.g. we could exclude such clients from BMCA entirely, but that means some of its data may not be updated (but then again, maybe that is fine?). Or we need to special-case some things in bmca

**Comment by davidv1992** [comment]
There is a statemachine specified for slave-only implementations on page 149. I think we should aim to produce similar observable results as that state machine.
