### ISSUE TITLE
Manual in conflict with binary

### ISSUE THREAD

**Issue by mdavids** [pendulum-project/statime#379]
It seems that the manual is in conflict with reality.

For example:

https://github.com/pendulum-project/statime/blob/079689ded247c0783ed7d48c63741bc7f7efae56/docs/man/statime.toml.5.md?plain=1#L72

Says `acceptable_master_list` whereas it should say` acceptable-master-list`.

I haven't verified, but at first glance this is the case for some other options as well. Like `hardware-clock`.

Also, some options appear to be missing from the man page, at least this is the case for `network-mode`.

**Comment by cikzh** [comment]
It should indeed be all in kebab-case. #385 will fix this. Thanks for mentioning this!
