### ISSUE TITLE
Parent Announce messages do not update datasets

### ISSUE THREAD

**Issue by Florob** [pendulum-project/statime#439]
In accordance with IEEE 1588-2019 section 9.5.3 incoming announce messages from the Parent PTP Instance shall update datasets the same as during BMCA. The difference being that values are coming from the incoming message instead of E<sub>best</sub>.
Currently statime doesn't do this. As a consequence values are only propagated after almost two announce intervals (worst case). A correct implementation would always propagate them after less than one announce interval.

## Underlying Issue
In the current design, as I understand it, datasets are immutably borrowed during regular operation, i.e. outside of BMCA. Therefore, `Port<Running, …>::handle_announce()` can not just update datasets. I had already stumbled over this while trying to implement Path Trace, which also wants to update its dataset in the same situation.

Some solutions I have considered:
1. Use a spin lock
    * "Works" on embedded targets
    * Can deadlock in interrupts occurring during lock (e.g. RTIC)
    * Wastes resources on systems with an OS
2. use [`critical_section`](https://docs.rs/critical-section)
    * Works on embedded targets
    * Disables interrupts on embedded (no deadlocks)
    * Global lock on systems with an OS, i.e. inhibits parallelism even in the absence of writes
3. Use atomics
    * Can only update one field at a time leading to inconsistencies
    * Not available for arrays (relevant for path trace)
    * More advanced ideas (e.g. keep each dataset twice, refer to them by `AtomicPtr`) all seem to run the risk of deadlock.
4. Refactor to not borrow the PTP Instance in ports, instead passing it as an argument where required
    * Can use the best available synchronization primitive: RTIC resource management, RWLock, etc.
    * Loose coupling (can pass the wrong instance to a port)
    * Major refactoring and API change

I think only 2 and 4 are actually workable. I'm happy to work on this if we can agree on a route to take.

**Comment by Florob** [comment]
So, after having [prototyped](https://github.com/m2lab/statime/tree/decoupled-ports) 4, I realized that it actually inhibits parallelism to a larger extend then `critical_section` would. Both `Port::handle_general_receive()` and `Port::handle_event_receive()` would require mutable borrows during their entire execution. It also makes the API surface fairly fragile as more functions might need mutability as development continues.

This lead me to [prototyping](https://github.com/m2lab/statime/tree/lock-trait) another option:

5. Refactor to not borrow the PTP Instance in ports, instead passing a generic RwLock-like object in
    * All the benefits and shortcomings of 4
    * Localized locking
    * Differentiates read/write at the actual critical section, not on function level

**Comment by davidv1992** [comment]
Hmm, the spec is quite vague here, on the one hand suggesting only the port dataset(s) needs to be updated, but on the other having no useful fields in there to update. I think your interpretation of just having to update all datafields is correct, though I am not a 100% sure on that.

I do believe the situation isn't as bad as you sketch it, taking at most 1 announce period to update the datasets, not two. I think current behavior should be acceptable in most circumstances, even if not quite up to spec, at least for now. I am going to need a bit more time to properly evaluate this, and as currently we are quite busy with other things, this might take a while (expect a month or so).

**Comment by davidv1992** [comment]
Also, out of curiosity, how did you discover this issue?

**Comment by Florob** [comment]
> Hmm, the spec is quite vague here, on the one hand suggesting only the port dataset(s) needs to be updated, but on the other having no useful fields in there to update. I think your interpretation of just having to update all datafields is correct, though I am not a 100% sure on that.

Having re-read the paragraph I agree that "data sets for the ingress PTP Port" is strange wording. I guess one could argue that the datasets of its PTP instance are also "for the port".

> I do believe the situation isn't as bad as you sketch it, taking at most 1 announce period to update the datasets, not two. I think current behavior should be acceptable in most circumstances, even if not quite up to spec, at least for now.

Can you make an argument as to why this would be the case? My reasoning is as follows:
Announce interval and BMCA run on separate timers, Therefore, the following is plausible:
* Announce message is sent
* BMCA runs
* Announce message is received
* Remaining announce interval passes
* Announce message containing old data is sent
* BMCA runs updating datasets
* Remaining announce interval passes
* Announce message containing new data is sent

In this situation (BMCA before Announce is received) it always takes $(1 + x) \cdot \textrm{AnnounceInterval}$ for data to propagate. Since $x$ can get close to $1$, I'm assuming that the worst case is "almost two announce intervals".
You are of course technically correct that it takes at most one announce interval to update the datasets. However, I'm concerned about propagation through the network, which can take an announce interval longer.

> Also, out of curiosity, how did you discover this issue?

I was working on an implementation of the Path Trace option (16.2). I was actually expecting this "issue" as correct behavior, but was surprised observing that other PTP implementation did never exhibit it. So I went back looking at the standard and trying to reason about possible timings.

**Comment by davidv1992** [comment]
I misunderstood and thought you meant announce in to updated datasets, which is shorter.

**Comment by davidv1992** [comment]
Apologies this took a bit longer than a month. Having given this some though, something along the lines of 5 seems like the best option to me, but with a minor modification. I think the most ergonomic option would to not pass that in as an argument but to keep the lock-type object around in the ports and instance. That would avoid the loose coupling issue for the most part (a determined programmer can still break that by making a completely bonkers implementation, but accidental mixups should be near impossible).

This is still not a major priority on our end to implement (I can still live with the mild delay), but feel free to make a merge request along those lines.
