### ISSUE TITLE
Async proposal

### ISSUE THREAD

**Issue by diondokter** [pendulum-project/statime#44]
## Async for Statime

PTP takes a lot of waiting. Waiting on messages and waiting on interval times.
Currently we have a network and a clock API that tries to get around this by leveraging callbacks. The runtime does something and then waits on a callback.

This works, but it's not very nice to use and work in. It splits up a lot of the logic and complicates having multiple ports (which we don't support yet). Async will solve a lot of these issues.

### Cons
- Everybody who uses statime needs an async runtime
  - Yes, but that doesn't mean it's got to be a very big one. On embedded we have multiple runtimes that would work.
- Async code can become complex
  - True, but I expect we're not gonna be touching anything complex. Only implementing the clock and network interfaces can get complex, but it doesn't have to if you make the right choices.
- Requires a nightly compiler (for now)

## Comparison

Let's look at the situation now and how it could be in async.

#### Currently:

- Call send through NetworkPort
	- Get back an ID
	- Store the id somewhere and remember that you need this timestamp to do calculations
- The implementation gets a send timestamp at some point from the hardware or kernel
	- Call `handle_send_timestamp` on the ptp instance
	- The timestamp gets routed to the port state
	- The slave state then remembers that it needed this timestamp and now uses it in the calculations
	
####  Async:
- Call send
- Get the timestamp
- Do the calculations

#### Currently:

There is a vestigial `recv` function on the NetworkRuntime that is never used and never implemented.
It's not a good place anyways because a receive doesn't go on the runtime but on the port.

Now all messages are routed to `handle_network` on the ptp instance and from there it is applied to the port. This only works with one port because there is no way to differentiate a message's port.

#### Async:

A receive function is added on the Network port.
A port can then just wait until a message is received.
This will require that every port needs to be polled whenever required.

#### Currently:

We need to wait on certain intervals. This will be more important once master mode is implemented.
The alarms are now the responsibility of the runtime implementor.

Different parts of the code can get a `Watch`. The watch has an ID.
On a watch you can set an alarm. When that alarm goes off the runtime implementor calls `handle_alarm` on the ptp-instance. From where based on the ID the runtime needs to do something.

#### Async:

You just await for a time. The implementation of this needs to be generic, but that's not difficult to implement. (Watch is a trait already)

**Comment by bramtweedegolf** [comment]
Agreed; using async would make the code clearer, IMO.

**Comment by davidv1992** [comment]
To what extend would this prevent/limit the ability to in the future write a C api layer to allow using the code in embedded environments where the majority of the software is written in C?
